//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfvbaibai.What2Eat.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public string Name { get; set; }
        public short Type { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
