//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfvbaibai.What2Eat.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealDetail
    {
        public int ID { get; set; }
        public byte MealTypeId { get; set; }
        public string MealTypeName { get; set; }
        public string DishName { get; set; }
        public Nullable<short> DishTypeId { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
    }
}
